services:
  fiscalize-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiscalize-api
    restart: unless-stopped
    ports:
      - '3366:3000'
      - '5555:5555'
    networks:
      - fiscalize-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    

  fiscalize-minio:
    container_name: fiscalize-minio
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    command: server /data --address ":9000" --console-address ":9001"
    restart: unless-stopped
    ports:
      - '9000:9000'   # API
      - '9001:9001'   # Console Web UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - fiscalize_minio_data:/data
    networks:
      - fiscalize-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

volumes:
  fiscalize_db_volume:
    driver: local
  fiscalize_minio_data:
    driver: local

networks:
  fiscalize-network:
    driver: bridge
